Create UserProfile Component (#62)
damdiana/beauty-app pull request #63
Opened 2023-06-24 11:00 UTC by damdiana

2023-06-26 13:46 UTC, iampava requested changes

2023-06-26 13:46 UTC, iampava commented on src/app/profile/layout.tsx
> +                  ? "p-1 bg-black text-white"
We should extract those strings into variables, and re-use them.

2023-06-26 13:46 UTC, iampava commented on src/components/UserProfile/UserFavorites.tsx
> +  return (
We can put this inside `favorites/page.tsx`. No need for a new component now, that is read only.

2023-06-26 13:46 UTC, iampava commented on src/components/EditableField/EditableField.tsx
> +          <form className="flex justify-betwee flex-col">
Are you sure this works when clicking `Enter`?

2023-06-26 14:13 UTC, iampava requested changes

2023-06-26 15:28 UTC, iampava requested changes

2023-06-26 15:28 UTC, iampava commented on src/components/EditableField/EditableField.tsx
> +const EditableField = ({ label, initialValue, type, onSave }: Props) => {
Let's add a storybook for this one

2023-06-26 15:28 UTC, iampava commented on src/components/UserProfile/UserSettings.tsx
> +function UserSettings() {
Remove from `UserProfile` folder. Put it directly in `components.

2023-06-26 15:39 UTC, damdiana commented on src/components/EditableField/EditableField.tsx
> +const EditableField = ({ label, initialValue, type, onSave }: Props) => {
Storybook currently not working

2023-06-28 19:06 UTC, iampava approved these changes
2 small changes needed + rename the issue. Afterwards you can merge

2023-06-28 19:06 UTC, iampava commented on src/components/EditableField.tsx
> +              <input
Shouldn't this be required? Did you check if I can save it while being empty?

2023-06-28 19:06 UTC, iampava commented on src/components/UserSettings.tsx
> +            label={"Full Name"}
No need to put the `{` if it's just a string. It can be simply `label="Full Name"`.

Do the same for all

2023-06-28 19:36 UTC, merged