Integrate giving a review with the API (#79)
damdiana/beauty-app pull request #80
Opened 2023-08-10 16:38 UTC by damdiana

2023-10-12 07:16 UTC, iampava requested changes

2023-10-12 07:16 UTC, iampava commented on src/components/ProductReviewsSection.tsx
> +    }
Actually no need for try-catch here. We have one inside `<FeedbackForm.tsx>`. Just make sure to change the state there

2023-10-12 07:16 UTC, iampava commented on src/components/FeedbackForm/FeedbackForm.tsx
> +          ))}
This should be extracted into a separate component

```tsx
const RatingButtons = ({
  rating,
  onRatingChange
}: {
  rating: number;
  onRatingChange: (newRating: number) => void;
}) => {
  // ...
}
```

2023-10-15 12:53 UTC, damdiana commented on src/app/api/product-reviews/[productId]/route.ts
> +    }
will extract this function after this PR is merged

2023-10-16 07:16 UTC, iampava approved these changes
After you remove that commented code, make sure to test everything works. If yes, then merge

2023-10-16 07:16 UTC, iampava commented on src/components/FeedbackForm/FeedbackForm.tsx
> +  // const onRatingChange = () => {
Why do we have this commented function? Delete if we don't need it

2023-10-16 08:24 UTC, merged